# Default values for kubevirt.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

kubevirt:
    namespace: kubevirt
    image:
        # ImagePullPolicy; valid values are "IfNotPresent", "Never", and "Always"
        pullPolicy: IfNotPresent
