apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdi-operator
  labels:
    name: cdi-operator
{{- include "cdi-operator.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cdi-operator
  strategy: {}
  template:
    metadata:
      labels:
        name: cdi-operator
    spec:
      containers:
      - env:
        - name: DEPLOY_CLUSTER_RESOURCES
          value: "true"
        - name: OPERATOR_VERSION
          value: {{ .Values.cdi.version | default .Chart.AppVersion }}
        - name: CONTROLLER_IMAGE
          value: {{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag | default .Chart.AppVersion }}
        - name: IMPORTER_IMAGE
          value: {{ .Values.importer.image.repository }}:{{ .Values.importer.image.tag | default .Chart.AppVersion }}
        - name: CLONER_IMAGE
          value: {{ .Values.cloner.image.repository }}:{{ .Values.cloner.image.tag | default .Chart.AppVersion }}
        - name: APISERVER_IMAGE
          value: {{ .Values.apiserver.image.repository }}:{{ .Values.apiserver.image.tag | default .Chart.AppVersion }}
        - name: UPLOAD_SERVER_IMAGE
          value: {{ .Values.uploadserver.image.repository }}:{{ .Values.uploadserver.image.tag | default .Chart.AppVersion }}
        - name: UPLOAD_PROXY_IMAGE
          value: {{ .Values.uploadproxy.image.repository }}:{{ .Values.uploadproxy.image.tag | default .Chart.AppVersion }}
        - name: VERBOSITY
          value: "1"
        - name: PULL_POLICY
          value: IfNotPresent
        image: {{ .Values.operator.image.repository }}:{{ .Values.operator.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.cdi.image.pullPolicy }}
        name: cdi-operator
        ports:
        - containerPort: 60000
          name: metrics
          protocol: TCP
        resources: {}
      securityContext:
        runAsNonRoot: true
      serviceAccountName: cdi-operator
